#!/usr/bin/env bun
// Bundle the viewer SPA + landing for the Worker's static assets.
// Since the entrypoint is HTML, main.tsx / styles.css are pulled in through index.html.
import { rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import tailwind from "bun-plugin-tailwind";

const entry = fileURLToPath(new URL("./viewer/index.html", import.meta.url));
const outdir = fileURLToPath(new URL("./viewer/dist", import.meta.url));

// Hashed filenames accumulate across builds, so rebuild from scratch each time
await rm(outdir, { recursive: true, force: true });

const result = await Bun.build({
  entrypoints: [entry],
  outdir,
  target: "browser",
  plugins: [tailwind],
  minify: true,
  // mermaid is already dynamic-imported (src/catalogs/Mermaid). Unlike binary
  // embedding, chunk splitting works for web delivery, so keep it out of the initial load
  // until a share containing a diagram is opened
  splitting: true,
  // Relative references from under /shares/<id> get swallowed by the SPA fallback, so use absolute paths
  publicPath: "/",
  define: { "process.env.NODE_ENV": JSON.stringify("production") },
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

// With splitting enabled, Bun 1.3.12 writes a non-entry-point chunk into the HTML's
// <script src> (a bug). The correct one is the output with kind === "entry-point", so repoint to it
const jsEntry = result.outputs.find(
  (o) => o.kind === "entry-point" && o.path.endsWith(".js"),
);
if (!jsEntry) {
  console.error("share viewer: no js entry-point in build outputs");
  process.exit(1);
}
const entryName = jsEntry.path.split("/").pop();
let html = await Bun.file(`${outdir}/index.html`).text();
const scriptSrc = html.match(/<script type="module"[^>]*\bsrc="([^"]+)"/)?.[1];
if (scriptSrc === undefined) {
  // The HTML's script shape changed and the workaround regex no longer matches. Bail to avoid deploying a blank page
  console.error("share viewer: could not locate the module <script src> to repoint");
  process.exit(1);
}
if (scriptSrc === `/${entryName}`) {
  // Already points at the entry = the Bun bug is fixed. This workaround can be removed
  console.warn("share viewer: HTML already references the entry chunk; the splitting workaround may be obsolete");
}
html = html.replace(/(<script type="module"[^>]*\bsrc=")[^"]+(")/, `$1/${entryName}$2`);
await Bun.write(`${outdir}/index.html`, html);

// With script-src 'self' as-is, the CSP rejects index.html's inline theme script.
// Take the sha256 of the inline script from the built HTML and write it to a generated file that the worker includes in the CSP
const hashes: string[] = [];
for (const match of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
  const body = match[1] ?? "";
  if (body.trim() === "") continue;
  const digest = new Bun.CryptoHasher("sha256").update(body).digest("base64");
  hashes.push(`'sha256-${digest}'`);
}
const generated = `// generated by share/build.ts — do not edit (CSP hash of the inline script)
export const VIEWER_INLINE_SCRIPT_HASHES: readonly string[] = ${JSON.stringify(hashes)};
`;
await Bun.write(fileURLToPath(new URL("./csp.generated.ts", import.meta.url)), generated);
console.log(`share viewer: built → ${outdir} (inline script hashes: ${hashes.length})`);
