#!/usr/bin/env bun
// viewer SPA + landing を Worker の static assets 用に bundle する。
// html entrypoint なので main.tsx / styles.css は index.html から辿って束ねられる。
import { rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import tailwind from "bun-plugin-tailwind";

const entry = fileURLToPath(new URL("./viewer/index.html", import.meta.url));
const outdir = fileURLToPath(new URL("./viewer/dist", import.meta.url));

// hash 付きファイル名が build ごとに溜まるので毎回作り直す
await rm(outdir, { recursive: true, force: true });

const result = await Bun.build({
  entrypoints: [entry],
  outdir,
  target: "browser",
  plugins: [tailwind],
  minify: true,
  // mermaid は dynamic import 済み (src/catalogs/MarkdownDoc/Mermaid)。binary 埋め込みと違い
  // Web 配信では chunk 分割が効くので、図を含む share を開くまで初回ロードから外す
  splitting: true,
  // /shares/<id> 配下から相対参照すると SPA fallback に飲まれるため絶対パスにする
  publicPath: "/",
  define: { "process.env.NODE_ENV": JSON.stringify("production") },
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

// Bun 1.3.12 は splitting 有効時、HTML の <script src> に entry-point でない chunk を
// 書き込む (bug)。outputs の kind === "entry-point" が正なので、そちらに張り直す
const jsEntry = result.outputs.find(
  (o) => o.kind === "entry-point" && o.path.endsWith(".js"),
);
if (!jsEntry) {
  console.error("share viewer: no js entry-point in build outputs");
  process.exit(1);
}
const entryName = jsEntry.path.split("/").pop();
let html = await Bun.file(`${outdir}/index.html`).text();
html = html.replace(/(<script type="module"[^>]*\bsrc=")[^"]+(")/, `$1/${entryName}$2`);
await Bun.write(`${outdir}/index.html`, html);

// CSP は script-src 'self' のままだと index.html の inline theme script を弾く。
// build 済み HTML から inline script の sha256 を採って生成ファイルに書き、worker が CSP に含める
const hashes: string[] = [];
for (const match of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
  const body = match[1] ?? "";
  if (body.trim() === "") continue;
  const digest = new Bun.CryptoHasher("sha256").update(body).digest("base64");
  hashes.push(`'sha256-${digest}'`);
}
const generated = `// generated by share/build.ts — do not edit (inline script の CSP hash)
export const VIEWER_INLINE_SCRIPT_HASHES: readonly string[] = ${JSON.stringify(hashes)};
`;
await Bun.write(fileURLToPath(new URL("./csp.generated.ts", import.meta.url)), generated);
console.log(`share viewer: built → ${outdir} (inline script hashes: ${hashes.length})`);
