#!/usr/bin/env bun
// Generate the Homebrew formula for wwwyo/homebrew-tap from a release's checksums.
//   bun generate-formula.ts <version> <checksums.txt>  →  formula on stdout
// Called by release.yml's homebrew job; the tap repo never holds generation logic,
// so the formula can only change through a release of this repo (single direction, no drift).

const [version, checksumsPath] = process.argv.slice(2);
if (!version || !checksumsPath) {
  console.error("usage: bun generate-formula.ts <version> <checksums.txt>");
  process.exit(1);
}

// sha256sum format: "<hex><spaces><filename>" per line.
const sums = new Map<string, string>();
for (const line of (await Bun.file(checksumsPath).text()).split("\n")) {
  const m = /^([0-9a-f]{64})\s+\*?(\S+)$/.exec(line.trim());
  if (m?.[1] && m[2]) sums.set(m[2], m[1]);
}

function sha(asset: string): string {
  const s = sums.get(asset);
  if (!s) {
    console.error(`generate-formula: ${asset} not found in ${checksumsPath}`);
    process.exit(1);
  }
  return s;
}

const base = `https://github.com/wwwyo/syokan/releases/download/v${version}`;

console.log(`\
# Generated by apps/syokan/scripts/generate-formula.ts in wwwyo/syokan (release ${version}).
# Do not edit by hand — the next release overwrites this file.
class Syokan < Formula
  desc "LLMs summon rich UI: post a JSON tree, an ephemeral view appears"
  homepage "https://github.com/wwwyo/syokan"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/syokan-darwin-arm64"
      sha256 "${sha("syokan-darwin-arm64")}"
    end
    on_intel do
      url "${base}/syokan-darwin-x64"
      sha256 "${sha("syokan-darwin-x64")}"
    end
  end

  on_linux do
    on_arm do
      url "${base}/syokan-linux-arm64"
      sha256 "${sha("syokan-linux-arm64")}"
    end
    on_intel do
      url "${base}/syokan-linux-x64"
      sha256 "${sha("syokan-linux-x64")}"
    end
  end

  def install
    bin.install Dir["syokan-*"].first => "syokan"
  end

  test do
    assert_match "${version}", shell_output("#{bin}/syokan --version")
  end
end`);
